### ISSUE TITLE
How updated is the --kernel feature ? 

### ISSUE THREAD

**Issue by boos** [slimm609/checksec.sh#10]
More a question than a issue. 

I'm using checksec.sh to evaluate quickly which grsec/pax options are turned on and I'm wondering about which options are checked ? 

In other words, is the tool checking all the kernel configuration available with the latest grsecurity/pax patch ?

**Comment by slimm609** [comment]
Not with the most recent. I normally try to keep track of and update important features. There are certain features that aren't security features and I don't normally include those

**Comment by boos** [comment]
K, now a feature request. 
What about adding a --kernel-all to list as is plus all not listed grsec/pax kernel_config found ?

**Comment by slimm609** [comment]
The security features are included but this like logging policy is not a feature directly related to security. Those are the things not included. I also normally try to include only the stable release as the other releases are almost daily.

**Comment by boos** [comment]
logging is a security feature :) 

If I'll implement something that print raw output of all the non-listed (with --kernel) configuration, will you accept the pull request ?
