### ISSUE TITLE
Fortify source false positives

### ISSUE THREAD

**Issue by disconnect3d** [slimm609/checksec.sh#103]
The fortify source detection can easily be hijacked by having a symbol that  contains `_chk` in its name like `stack_chk_guard` or `stack_chk_fail`. This can be observed below, where one program has additional `x_chk` symbol that we think makes the binary having fortify-source mitigation.

![image](https://user-images.githubusercontent.com/10009354/58275730-10af4880-7d96-11e9-98cf-8b97ccedbab9.png)

This happens on current master or a git commit 396748730e22ab5e2cd3b8ce9268a1f0afcfb964.

I believe the relevant part of the code is this:
https://github.com/slimm609/checksec.sh/blob/396748730e22ab5e2cd3b8ce9268a1f0afcfb964/checksec#L486-L495

**Comment by slimm609** [comment]
the dynamic symbols should fix the issue.  I tested against your provided code and it no longer reports as a false positive. please open a new ticket if it still exists or if you find a new way.   

thanks!

**Comment by disconnect3d** [comment]
Thanks!
