### ISSUE TITLE
Symbolic Links Handling

### ISSUE THREAD

**Issue by mircean1** [slimm609/checksec.sh#104]
Hello, this is not a issue, but more as an improvement.
I have many symbolic links (like busybox tools) and I would like to have the possibility to skip them. Maybe an option "--ignore-sym-link" would help.
I am using checksec for reporting and testing and I would like to ignore symlinks, not to report 400 files instead of 300.

Thanks!

**Comment by slimm609** [comment]
which options were you using?   need more info

**Comment by slimm609** [comment]
fixed in new release (hopefully today)
