### ISSUE TITLE
repository versionning since last update

### ISSUE THREAD

**Issue by mathieu-aubin** [slimm609/checksec.sh#105]
## Issue
Would enjoy if there was a possibility of updating everything to match the version update from 21 days ago (today anyways)... sig, rpm spec, changelog... etc....

Essentially, for package maintainers

## Debug Report
N/A

## Command run to produce the error
N/A

## OS version and Kernel version
N/A

## Debug output
N/A

**Comment by slimm609** [comment]
I will try to get a new signed update out tonight

**Comment by mathieu-aubin** [comment]
I was close to submitting a PR about all that stuff that requires modifications.. i decided not too because of the signed part of it. Are you signing with a personnal gpg-key and if so, have you considered alternative methods that could make the whole process of updating version and version infos in required files?

a tiny bash script that parses all files for an input, per say, and replaces it with the new version number..
as far a (if) you are using personnal gpg key to sign, maybe you could take advantage of Git pre/post-commit hooks to check if file has changed and a signature needs to be added to the commit... maybe? i,m sure there are lots of ways

**Comment by slimm609** [comment]
The reason the file is signed is because the --update flag in the script, pulls and verifies the signature locally.     The whole thing is scripted and easy to do but I recently got a new machine and the gpg key wasn't moved over so I had everything to sign it except the key.        Its good now though
