### ISSUE TITLE
"Symtable" diffent message when exporting to csv

### ISSUE THREAD

**Issue by tawmoto** [slimm609/checksec.sh#107]
I run checksec with console output and then with csv output, I get different string results.

```
Full RELRO      Canary found      NX enabled    PIE enabled     No RPATH   RUNPATH     No Symbols      Yes	4		14	./apc_random_id_generator

Full RELRO,Canary found,NX enabled,PIE enabled,No RPATH,RUNPATH,No SYMTABLES,Yes,4,14,./apc_random_id_generator
```

Why is "No Symbols" and "No SYMTABLES" different strings?
Thanks

**Comment by slimm609** [comment]
They are the same thing.    Symtable is the name of the symbols table

**Comment by tawmoto** [comment]
Yes, thank you, I know that they are the same, I was wondering if there is a special reason on why they are named in the outputs. All the others are the same.
Best regards

**Comment by slimm609** [comment]
being fixed to symbols in the newest version
