### ISSUE TITLE
2.0.0 usage advertises "--output {cli|csv|xml|json}" but should be "--format={cli,csv,xml,json}"?

### ISSUE THREAD

**Issue by hartwork** [slimm609/checksec.sh#108]
With 2.0.0 I noticed soemthing odd in husage/help output:
```console
# checksec | fgrep cli
Usage: checksec [--output {cli|csv|xml|json}] [OPTION]
  --format=[cli|csv|xml|json]
```
I find:
- `--output` is used without `=` and should be `--format` instead
- Inconsistent use of `[..]` versus `{..}` versus `<..>`

I would suggest to use `[..]` for optional things only, e.g. not for the right side of `--format=`.

On a side note, `checksec [--format={cli,csv,xml,json}] [OPTION]` would still advertise plain `checksec` as avalid way to call while it seems to need one of `--proc-all` and frieds, at least. It would be great to communicate that better. Happy to make a dedicated ticket for that.

Thank you!

**Comment by hartwork** [comment]
PS: Here's how Python's stdlib argpargse would format things, for comparison/inspiration:
```console
# python -c 'import argparse; p = argparse.ArgumentParser(prog="checksec.sh"); p.add_argument("--format", choices=["json", "xml"]); print(p.format_help())'
usage: checksec.sh [-h] [--format {json,xml}]

optional arguments:
  -h, --help           show this help message and exit
  --format {json,xml}
```

**Comment by hartwork** [comment]
PPS: The man page also still mentions `-o or --output`

**Comment by slimm609** [comment]
updated.   switched to all {..} for required options and [..] for optional.    should resolve all other issues

--output= and --format= are interchangeable but usage is now consistent

**Comment by slimm609** [comment]
if it looks good, i will release as 2.0.1

**Comment by hartwork** [comment]
> --output= and --format= are interchangeable but usage is now consistent

Cannot confirm, `--output` does not seem to work at all:
```console
# checksec --output=csv --proc-all
Error: Unknown option output=csv.
```
Cannot find anything for `output=` in the 2.0.0 code either.

**Comment by slimm609** [comment]
its in master, not in 2.0.0 .   it used to be there and got removed in 2.0.0 but just added it back

```
$ ./checksec --output=xml
<?xml version="1.0" encoding="UTF-8"?>
Error: No option selected. Please select an option.

$ ./checksec --format=xml
<?xml version="1.0" encoding="UTF-8"?>
Error: No option selected. Please select an option.
```

**Comment by hartwork** [comment]
I see now you were referring to the next release here, found your change at for `format=*|output=*)` now.

**Comment by hartwork** [comment]
> if it looks good, i will release as 2.0.1

From a quick look, e6b98219aaf3b54c8597b15ed81bf77ea8f7c60a#diff-4de72339214a2b81caab117fb4aac50aR1835 looks pretty good to me.

**Comment by slimm609** [comment]
2.0.1 released.   Closing issue

if you find any other issues, please open a new issue. 

Thanks @hartwork

**Comment by hartwork** [comment]
[Bumped to 2.0.1 in Gentoo](https://github.com/gentoo/gentoo/commit/6aa766dcc79dab122ce43be0beb296050d8b421d) now.
