### ISSUE TITLE
Where is the Clang CFI and SafeStack checks?

### ISSUE THREAD

**Issue by cypherbits** [slimm609/checksec.sh#110]
On https://github.com/slimm609/checksec.sh/releases/tag/2.0.0 we have 

> * checksec.sh: adds Clang CFI and SafeStack checks
>Thanks dobin

where is this exactly?

**Comment by slimm609** [comment]
https://github.com/slimm609/checksec.sh/pull/94/files

**Comment by slimm609** [comment]
this was actually closed but looks like it got included in the release notes

**Comment by slimm609** [comment]
GCC doesn't support clang or safestack

**Comment by slimm609** [comment]
removed from the release notes and changelog is being updated.

**Comment by cypherbits** [comment]
Ok, nice.

**Comment by slimm609** [comment]
Clang CFI and safe-stack has been added as `--extended` checks
