### ISSUE TITLE
RW_RPATH check alerts on root:root 755 dirs

### ISSUE THREAD

**Issue by lamont-granquist** [slimm609/checksec.sh#119]
We got a report about a RW_RPATH violation that this tool turned up and I've looked into and the directory should be 755 and root:root owned.  Looking at your code, it looks like it will alert off of those perms:

https://github.com/slimm609/checksec.sh/blob/fd840bcf3aeeb105dd83374ed80fce226ba0bc4b/checksec#L438

Not sure if I'm missing something but I don't think that should be considered a violation.

And my bash-fu is pretty rusty but I don't think you're checking the parent directory perms and walking back up the directory heirarchy, or checking ownership perms, all of which could cause problems.

**Comment by Maryse47** [comment]
You can see in the code below that non-RW RPATH  is also considered as violation. Only no RPATH at all is ok. Note about RW is just additional info and you have to decide yourself if this is ok for your case.
