### ISSUE TITLE
do not show "Hardened Usercopy Pagespan: Disabled" as issue / CONFIG_HARDENED_USERCOPY_PAGESPAN=y

### ISSUE THREAD

**Issue by adrelanos** [slimm609/checksec.sh#122]
https://groups.google.com/d/msg/syzkaller-bugs/wt3NikTfotQ/zJnFApHtBAAJ

> Basically, yes. CONFIG_HARDENED_USERCOPY_PAGESPAN=y should not be used -- it's for tracking down these cases (not really for general-purpose "debugging"), but no one is currently working on solving them.

https://patchwork.kernel.org/patch/10565519/

> PAGESPAN checking is buggy for a lot of reasons, unfortunately. It
> should generally stay disabled unless someone is working on getting
> rid of allocations that _should_ have marked themselves as spanning
> pages. It's unclear if this is even a solvable problem in the kernel
> right now due to how networking code manages skbs.

**Comment by Maryse47** [comment]
https://github.com/slimm609/checksec.sh/pull/123
