### ISSUE TITLE
Kernel objects/modules (ELFs) listed as 'Not an ELF' in PIE protection output

### ISSUE THREAD

**Issue by slinkyy** [slimm609/checksec.sh#128]
## Issue
Any kernel object (.ko) files or modules are listed as ‘Not an ELF file’. This only occurs when checking ‘PIE’ protections of a binary.

This is due to ‘readelf -h’ being used to determine the ‘type’ of the ELF file and since ‘REL’ (Relocatable) is not within the conditional statements, it is simply labelled as not being an ELF via the ‘else’ clause.

Rather than stating 'Not an ELF file' it should state 'REL' or 'Relocatable' since they are valid ELF formatted files.

## Debug Report
This can be found in the checksec script on line: ‘406’
```
  # check for PIE support
  ${debug} && echo -e "\n***function filecheck->pie"
  if ${readelf} -h "${1}" 2>/dev/null | grep -q 'Type:[[:space:]]*EXEC'; then
    echo_message '\033[31mNo PIE       \033[m   ' 'No PIE,' ' pie="no"' '"pie":"no",'
  elif ${readelf} -h "${1}" 2>/dev/null | grep -q 'Type:[[:space:]]*DYN'; then
    if ${readelf} -d "${1}" 2>/dev/null | grep -q 'DEBUG'; then
      echo_message '\033[32mPIE enabled  \033[m   ' 'PIE enabled,' ' pie="yes"' '"pie":"yes",'
    else
      echo_message '\033[33mDSO          \033[m   ' 'DSO,' ' pie="dso"' '"pie":"dso",'
    fi
  else
    echo_message '\033[33mNot an ELF file\033[m   ' 'Not an ELF file,' ' pie="not_elf"' '"pie":"not_elf",'
  fi
```

Output of readelf -h on an example ‘.ko’ kernel object file:

```
$ readelf -h /lib/modules/5.3.0-7625-generic/kernel/block/bfq.ko
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
--snip---
```

## Command run to produce the error
```
$ ./checksec --file="/lib/modules/5.3.0-7625-generic/kernel/block/bfq.ko" --output=csv
No RELRO,Canary found,NX disabled,Not an ELF file,No RPATH,No RUNPATH,Symbols,No,0,0,/lib/modules/5.3.0-7625-generic/kernel/block/bfq.ko
```

## OS version and Kernel version
Linux pop-os 5.3.0-7625-generic

## Debug output

$ ./checksec --file="/lib/modules/5.3.0-7625-generic/kernel/block/bfq.ko" --output=csv --debug
***function filecheck
***function filecheck->RELRO
No RELRO,
***function filecheck->canary
Canary found,
***function filecheck->nx
NX disabled,
***function filecheck->pie
Not an ELF file,
***function filecheck->rpath
No RPATH,
***function filecheck->runpath
No RUNPATH,Symbols,***function filecheck->fortify
No,0,0,/lib/modules/5.3.0-7625-generic/kernel/block/bfq.ko

**Comment by slimm609** [comment]
fix in upcoming 2.2.0 release
