### ISSUE TITLE
NX stack checking is incomplete

### ISSUE THREAD

**Issue by noloader** [slimm609/checksec.sh#132]
I was looking through the source code for [`checksec` master](https://github.com/slimm609/checksec.sh/blob/master/checksec). The NX stack checking code is shown below.

```
  # check for NX support
  ${debug} && echo -e "\n***function filecheck->nx"
  if ${readelf} -W -l "${1}" 2>/dev/null | grep -q 'GNU_STACK'; then
    if ${readelf} -W -l "${1}" 2>/dev/null | grep 'GNU_STACK' | grep -q 'RWE'; then
      echo_message '\033[31mNX disabled\033[m   ' 'NX disabled,' ' nx="no"' '"nx":"no",'
    else
      echo_message '\033[32mNX enabled \033[m   ' 'NX enabled,' ' nx="yes"' '"nx":"yes",'
    fi
  else
    echo_message '\033[31mNX disabled\033[m   ' 'NX disabled,' ' nx="no"' '"nx":"no",'
  fi
```

The code is mostly right. It checks for a `GNU_STACK` header, and verifies it is W^X. However, for ELF binaries, the size of the stack segment must also be 0. A non-0 size indicates an executable stack. (The size comes from a nested function trampoline).

So this would be correct. It is all 0's.

```
$ readelf -l /bin/ls | grep -A 1 -i GNU_STACK
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  ...
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
```

And this is an executable stack in disguise, if I recall correctly. What happens is, there's a silent loss of NX stacks by the runtime loader. The loader will mark the stack executable when it loads the program due to a non-0 size.

```
$ readelf -l foobar | grep -A 1 -i GNU_STACK
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  ...
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000010 0x0000000000000000  RW     0x10
```

I only know about the detail because I asked the Binutil folks about it back in 2010 or 2012. I can't find the message at the moment to provide a citation. But it is one of those factoids that has stuck with me.

And related, I believe you will need to use another tool to check for NX stacks on Gentoo. The tool's name is `scanelf`. The reason you need a different tool for Gentoo is, Gentoo is a PaX-enabled kernel.

`scanelf` output would look similar to below. For `scanelf`, the capitol ***`M`*** in the thrid column is what you are looking for. Lower ***`m`*** is bad. I believe the ***`M`*** means the page has `PF_MPROTECT` permissions on it (but I may be mistaken).

```
$ scanelf -x foobar
TYPE     PAX   FILE
ET_DYN --Mxe- foobar
```

**Comment by slimm609** [comment]
Pax enabled kernels haven't had this problem from what I have seen,   W^X is BSD, which is not supported

**Comment by noloader** [comment]
You incorrectly closed this issue. Linux is sensitive to the non-0 stack size.

**Comment by slimm609** [comment]
You are welcome to submit PRs, unfortunately I don’t currently have time to look into this

**Comment by slimm609** [comment]
This should be resolved in the main branch
