### ISSUE TITLE
Checksec is not working on Solaris SunOS 5.11 11.4.0.15.0 sun4v sparc sun4v

### ISSUE THREAD

**Issue by shvo123** [slimm609/checksec.sh#172]
# Issue tracker
 If any of these values are not included, the issue will be closed and not worked

## Debug Report
include the output of `checksec --debug_report`

## Debug output

Run the same command as above to reproduce the error but include the --debug flag

e.x  `checksec --debug -f /usr/bin/ls`

**Comment by shvo123** [comment]
~/checksec/checksec
WARNING: 'sysctl' not found! It's required for most checks.

WARNING: Not all necessary commands found. Some tests might not work!

**Comment by slimm609** [comment]
solaris is missing lots of features needed for checksec to work properly and there is no plans to support.  even harder on sparc processors.
