### ISSUE TITLE
The method of checking whether so file used PIC is wrong. 

### ISSUE THREAD

**Issue by freeBoyfeny** [slimm609/checksec.sh#174]
The method of checking whether it is PIC is wrong. You can use the following methods 
 
readelf -d  lib*.so |grep TEXTREL

If the output is null, the so file must has used the -fPIC option.

**Comment by slimm609** [comment]
Can you provide more context here?    Which check specifically?

**Comment by slimm609** [comment]
Closing due to lack of followup
