### ISSUE TITLE
kernel check produces invalid JSON

### ISSUE THREAD

**Issue by jstucke** [slimm609/checksec.sh#177]
## Issue
The `--kernel` option in combination with JSON output occasionally produces invalid json.

## Debug Report

<details>
***** Checksec debug *****
uid=1000(redacted) gid=1000(redacted) groups=1000(redacted),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),114(lpadmin),134(sambashare),999(microk8s),1001(docker)
Linux redacted-ryzen-mint20 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
checksec version: 2.4.0 -- 2020081501
OS=Linux Mint
VER=20.1
-rwxr-xr-x 1 root root 43416 Sep  5  2019 /bin/cat
/bin/cat: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b357ed53c8c9cb1a312f83b28982304effae0135, for GNU/Linux 3.2.0, stripped
lrwxrwxrwx 1 root root 21 Jun 30  2020 /usr/bin/awk -> /etc/alternatives/awk
-rwxr-xr-x 1 root root 711136 Nov  3  2019 /usr/bin/gawk
/usr/bin/gawk: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b863ebf57d3cc33d8e7fed3be0e0b5d235489b46, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 30960 Mar 24 19:51 /sbin/sysctl
/sbin/sysctl: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=96ac80308734bb2b96c3e9986460f62163040214, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 39288 Sep  5  2019 /bin/uname
/bin/uname: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=3354931bca4ff072b26258a956ffde08ead5f341, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 47448 Sep  5  2019 /bin/mktemp
/bin/mktemp: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=cd6eaf6c3773543335f009051580413f0cdcd905, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 753336 Apr 28 02:37 /usr/bin/openssl
/usr/bin/openssl: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b32cf583738a560556a17e9fc1c0e83c5ea88035, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 199136 Jan 29  2020 /bin/grep
/bin/grep: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f4564437ed282494b69a191fcb07a56235cce8ff, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 88440 Sep  5  2019 /usr/bin/stat
/usr/bin/stat: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=327cb96d448045d5b7a10dfcda6bd0282a3a8b41, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 27104 Jan 16  2020 /usr/bin/file
/usr/bin/file: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=32715f59ea258e8fdf0dd8763fc501f958b0c4d6, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 320160 Feb 18  2020 /usr/bin/find
/usr/bin/find: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b8b9756abacab10f704aec42954e3fd2292f1e85, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 47480 Sep  5  2019 /usr/bin/head
/usr/bin/head: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=ce008644d1531db879a7698fde5952af3b9d5951, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 137688 Mar 24 19:51 /bin/ps
/bin/ps: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=16d93a83c5cf93faf21d4b833c822d49bdb76674, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 51544 Sep  5  2019 /bin/readlink
/bin/readlink: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=fd0a00264061ff768015704e147ee829e05d55c0, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 39256 Sep  5  2019 /usr/bin/basename
/usr/bin/basename: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d789f6a92a3ead8bb44badf3208926095d0c5b0b, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 47480 Sep  5  2019 /usr/bin/id
/usr/bin/id: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f8db9064d2203f35fa4c3c30f6ec4b0b7c614b5f, for GNU/Linux 3.2.0, stripped
lrwxrwxrwx 1 root root 10 Jun 30  2020 /usr/bin/which -> /bin/which
-rwxr-xr-x 1 root root 946 Dec  7  2019 /bin/which
/bin/which: POSIX shell script, ASCII text executable
-rwxr-xr-x 1 root root 548568 Jul 24  2019 /usr/bin/wget
/usr/bin/wget: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=844ac99e93a029c9bfc6b91a711f3f1084cc6e97, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 239848 Mar 23 14:13 /usr/bin/curl
/usr/bin/curl: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=530fc4785fd057433dea5d1e89bc288c39a81bad, for GNU/Linux 3.2.0, stripped
lrwxrwxrwx 1 root root 24 Jan 21 16:23 /usr/bin/readelf -> x86_64-linux-gnu-readelf
-rwxr-xr-x 1 root root 658360 Jan 21 16:23 /usr/bin/x86_64-linux-gnu-readelf
/usr/bin/x86_64-linux-gnu-readelf: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=12abee6b4885f190822c4174363e104734212e64, for GNU/Linux 3.2.0, stripped
*** can not find command eu-readelf
</details>

## Command run to produce the error

```bash
./checksec --kernel=tests/kernel.config --format=json 2>/dev/null | jq
parse error: Expected separator between values at line 1, column 448
```

The culprit is a missing comma before the "grsecurity" section (full output in "Debug output" section):
```
(...),"selinux":{ "enabled":"no" }"grsecurity": { (...)
```

## OS version and Kernel version
Linux Mint 20.1, 5.4.0-74-generic

## Debug output

<details>
***function kernelcheck
{ "kernel": { "KernelConfig":"/home/jstucke/git/checksec/bin/tests/kernel.config"CONFIG_GRKERNSEC=y
CONFIG_GRKERNSEC_CONFIG_AUTO=y
# CONFIG_GRKERNSEC_CONFIG_CUSTOM is not set
CONFIG_GRKERNSEC_CONFIG_SERVER=y
# CONFIG_GRKERNSEC_CONFIG_DESKTOP is not set
CONFIG_GRKERNSEC_CONFIG_VIRT_NONE=y
# CONFIG_GRKERNSEC_CONFIG_VIRT_GUEST is not set
# CONFIG_GRKERNSEC_CONFIG_VIRT_HOST is not set
# CONFIG_GRKERNSEC_CONFIG_PRIORITY_PERF is not set
CONFIG_GRKERNSEC_CONFIG_PRIORITY_SECURITY=y
CONFIG_GRKERNSEC_PROC_GID=1001
CONFIG_GRKERNSEC_TPE_UNTRUSTED_GID=1005
CONFIG_GRKERNSEC_SYMLINKOWN_GID=1006
CONFIG_GRKERNSEC_KMEM=y
CONFIG_GRKERNSEC_IO=y
CONFIG_GRKERNSEC_JIT_HARDEN=y
CONFIG_GRKERNSEC_PERF_HARDEN=y
CONFIG_GRKERNSEC_RAND_THREADSTACK=y
CONFIG_GRKERNSEC_PROC_MEMMAP=y
CONFIG_GRKERNSEC_BRUTE=y
CONFIG_GRKERNSEC_MODHARDEN=y
CONFIG_GRKERNSEC_HIDESYM=y
CONFIG_GRKERNSEC_KERN_LOCKOUT=y
# CONFIG_GRKERNSEC_NO_RBAC is not set
CONFIG_GRKERNSEC_ACL_HIDEKERN=y
CONFIG_GRKERNSEC_ACL_MAXTRIES=3
CONFIG_GRKERNSEC_ACL_TIMEOUT=30
CONFIG_GRKERNSEC_PROC=y
# CONFIG_GRKERNSEC_PROC_USER is not set
CONFIG_GRKERNSEC_PROC_USERGROUP=y
CONFIG_GRKERNSEC_PROC_ADD=y
CONFIG_GRKERNSEC_LINK=y
CONFIG_GRKERNSEC_SYMLINKOWN=y
CONFIG_GRKERNSEC_FIFO=y
CONFIG_GRKERNSEC_SYSFS_RESTRICT=y
# CONFIG_GRKERNSEC_ROFS is not set
CONFIG_GRKERNSEC_DEVICE_SIDECHANNEL=y
CONFIG_GRKERNSEC_CHROOT=y
CONFIG_GRKERNSEC_CHROOT_MOUNT=y
CONFIG_GRKERNSEC_CHROOT_DOUBLE=y
CONFIG_GRKERNSEC_CHROOT_PIVOT=y
CONFIG_GRKERNSEC_CHROOT_CHDIR=y
CONFIG_GRKERNSEC_CHROOT_CHMOD=y
CONFIG_GRKERNSEC_CHROOT_FCHDIR=y
CONFIG_GRKERNSEC_CHROOT_MKNOD=y
CONFIG_GRKERNSEC_CHROOT_SHMAT=y
CONFIG_GRKERNSEC_CHROOT_UNIX=y
CONFIG_GRKERNSEC_CHROOT_FINDTASK=y
CONFIG_GRKERNSEC_CHROOT_NICE=y
CONFIG_GRKERNSEC_CHROOT_SYSCTL=y
CONFIG_GRKERNSEC_CHROOT_CAPS=y
CONFIG_GRKERNSEC_CHROOT_INITRD=y
# CONFIG_GRKERNSEC_AUDIT_GROUP is not set
# CONFIG_GRKERNSEC_EXECLOG is not set
CONFIG_GRKERNSEC_RESLOG=y
# CONFIG_GRKERNSEC_CHROOT_EXECLOG is not set
# CONFIG_GRKERNSEC_AUDIT_PTRACE is not set
# CONFIG_GRKERNSEC_AUDIT_CHDIR is not set
# CONFIG_GRKERNSEC_AUDIT_MOUNT is not set
CONFIG_GRKERNSEC_SIGNAL=y
# CONFIG_GRKERNSEC_FORKFAIL is not set
CONFIG_GRKERNSEC_TIME=y
CONFIG_GRKERNSEC_PROC_IPADDR=y
CONFIG_GRKERNSEC_RWXMAP_LOG=y
CONFIG_GRKERNSEC_DMESG=y
CONFIG_GRKERNSEC_HARDEN_PTRACE=y
CONFIG_GRKERNSEC_PTRACE_READEXEC=y
CONFIG_GRKERNSEC_SETXID=y
CONFIG_GRKERNSEC_TPE=y
# CONFIG_GRKERNSEC_TPE_ALL is not set
# CONFIG_GRKERNSEC_TPE_INVERT is not set
CONFIG_GRKERNSEC_TPE_GID=1005
CONFIG_GRKERNSEC_RANDNET=y
CONFIG_GRKERNSEC_BLACKHOLE=y
CONFIG_GRKERNSEC_NO_SIMULT_CONNECT=y
CONFIG_GRKERNSEC_SOCKET=y
# CONFIG_GRKERNSEC_SOCKET_ALL is not set
# CONFIG_GRKERNSEC_SOCKET_CLIENT is not set
# CONFIG_GRKERNSEC_SOCKET_SERVER is not set
CONFIG_GRKERNSEC_DENYUSB=y
# CONFIG_GRKERNSEC_DENYUSB_FORCE is not set
CONFIG_GRKERNSEC_SYSCTL=y
# CONFIG_GRKERNSEC_SYSCTL_DISTRO is not set
CONFIG_GRKERNSEC_SYSCTL_ON=y
CONFIG_GRKERNSEC_FLOODTIME=10
CONFIG_GRKERNSEC_FLOODBURST=6
CONFIG_PAX_KERNEXEC_PLUGIN=y
CONFIG_PAX_PER_CPU_PGD=y
CONFIG_PAX_USERCOPY_SLABS=y
CONFIG_PAX=y
# CONFIG_PAX_SOFTMODE is not set
CONFIG_PAX_EI_PAX=y
CONFIG_PAX_PT_PAX_FLAGS=y
CONFIG_PAX_XATTR_PAX_FLAGS=y
# CONFIG_PAX_NO_ACL_FLAGS is not set
CONFIG_PAX_HAVE_ACL_FLAGS=y
# CONFIG_PAX_HOOK_ACL_FLAGS is not set
CONFIG_PAX_NOEXEC=y
CONFIG_PAX_PAGEEXEC=y
# CONFIG_PAX_EMUTRAMP is not set
CONFIG_PAX_MPROTECT=y
# CONFIG_PAX_MPROTECT_COMPAT is not set
# CONFIG_PAX_ELFRELOCS is not set
CONFIG_PAX_KERNEXEC=y
CONFIG_PAX_KERNEXEC_PLUGIN_METHOD_BTS=y
# CONFIG_PAX_KERNEXEC_PLUGIN_METHOD_OR is not set
CONFIG_PAX_KERNEXEC_PLUGIN_METHOD="bts"
CONFIG_PAX_ASLR=y
CONFIG_PAX_RANDKSTACK=y
CONFIG_PAX_RANDUSTACK=y
CONFIG_PAX_RANDMMAP=y
CONFIG_PAX_MEMORY_SANITIZE=y
CONFIG_PAX_MEMORY_STACKLEAK=y
CONFIG_PAX_MEMORY_STRUCTLEAK=y
CONFIG_PAX_MEMORY_UDEREF=y
CONFIG_PAX_REFCOUNT=y
CONFIG_PAX_USERCOPY=y
# CONFIG_PAX_USERCOPY_DEBUG is not set
CONFIG_PAX_CONSTIFY_PLUGIN=y
CONFIG_PAX_SIZE_OVERFLOW=y
CONFIG_PAX_LATENT_ENTROPY=y
, "randomize_va_space":"full", "nx_protection":"yes", "protect_symlinks":"no", "protect_hardlinks":"no", "protect_fifos":"unsupported", "protect_regular":"unsupported", "ipv4_rpath":"no", "kernel_heap_randomization":"yes", "gcc_stack_protector":"yes", "random_address_space_layout":"yes"},
***fuction getsestatus
"selinux":{ "enabled":"no" }"grsecurity": { "grsecurity_config":"auto", "config_pax_kernexec":"yes", "config_pax_noexec":"yes", "config_pax_pageexec":"yes", "config_pax_mprotect":"yes", "config_pax_aslr":"yes", "config_pax_randkstack":"yes", "config_pax_randustack":"yes", "config_pax_randmmap":"yes", "config_pax_memory_sanitize":"yes", "config_pax_memory_stackleak":"yes", "config_pax_memory_uderef":"yes", "config_pax_refcount":"yes", "config_pax_usercopy":"yes", "config_grkernsec_jit_harden":"yes", "config_grkernsec_rand_threadstack":"yes", "config_grkernsec_kmem":"yes", "config_grkernsec_io":"yes", "config_grkernsec_modharden":"yes", "config_grkernsec_chroot":"yes", "config_grkernsec_harden_ptrace":"yes", "config_grkernsec_randnet":"yes", "config_grkernsec_blackhole":"yes", "config_grkernsec_brute":"yes", "config_grkernsec_hidesym":"yes", "pax_softmode":"no" }, "grsecurity_sysctl": {, "grsec_sysctl_audit_chdir":"no", "grsec_sysctl_audit_gid":"no", "grsec_sysctl_audit_group":"no", "grsec_sysctl_audit_mount":"no", "grsec_sysctl_audit_ptrace":"no", "grsec_sysctl_chroot_caps":"no", "grsec_sysctl_chroot_deny_bad_rename":"no", "grsec_sysctl_chroot_deny_chmod":"no", "grsec_sysctl_chroot_deny_chroot":"no", "grsec_sysctl_chroot_deny_fchdir":"no", "grsec_sysctl_chroot_deny_mknod":"no", "grsec_sysctl_chroot_deny_mount":"no", "grsec_sysctl_chroot_deny_pivot":"no", "grsec_sysctl_chroot_deny_shmat":"no", "grsec_sysctl_chroot_deny_sysctl":"no", "grsec_sysctl_chroot_deny_unix":"no", "grsec_sysctl_chroot_enforce_chdir":"no", "grsec_sysctl_chroot_execlog":"no", "grsec_sysctl_chroot_findtask":"no", "grsec_sysctl_chroot_restrict_nice":"no", "grsec_sysctl_consistent_setxid":"no", "grsec_sysctl_deny_new_usb":"no", "grsec_sysctl_deter_bruteforce":"no", "grsec_sysctl_disable_priv_io":"no", "grsec_sysctl_dmesg":"no", "grsec_sysctl_enforce_symlinksifowner":"no", "grsec_sysctl_exec_logging":"no", "grsec_sysctl_fifo_restrictions":"no", "grsec_sysctl_forkfail_logging":"no", "grsec_sysctl_grsec_lock":"no", "grsec_sysctl_harden_ipc":"no", "grsec_sysctl_harden_ptrace":"no", "grsec_sysctl_ip_blackhole":"no", "grsec_sysctl_lastack_retries":"no", "grsec_sysctl_linking_restrictions":"no", "grsec_sysctl_ptrace_readexec":"no", "grsec_sysctl_resource_logging":"no", "grsec_sysctl_romount_protect":"no", "grsec_sysctl_rwxmap_logging":"no", "grsec_sysctl_signal_logging":"no", "grsec_sysctl_socket_all":"no", "grsec_sysctl_socket_all_gid":"no", "grsec_sysctl_socket_client":"no", "grsec_sysctl_socket_client_gid":"no", "grsec_sysctl_socket_server":"no", "grsec_sysctl_socket_server_gid":"no", "grsec_sysctl_symlinkown_gid":"no", "grsec_sysctl_timechange_logging":"no", "grsec_sysctl_harden_tty":"no", "grsec_sysctl_tpe":"no", "grsec_sysctl_tpe_gid":"no", "grsec_sysctl_tpe_invert":"no", "grsec_sysctl_tpe_restrict_all":"no" } }
</details>

## Notes

It would be great if there was an option to run checksec only on the kernel config file (and not on the running kernel) to be able to check kenel configurations from other devices (e.g. kernel configs extracted from embedded devices or firmware)

**Comment by slimm609** [comment]
Checksec can run on any kernel config that you pass it.   The kernel config test runs against 15+ different config files. 

this command checks a kernel that it is not running on.

```
./checksec --kernel=tests/kernel.config --format=json
```

**Comment by slimm609** [comment]
I see the issue with the json format and am working on a fix for it.   the odd thing is the tests are passing but when i run the same test by hand it fails so want to figure out why that is happening

**Comment by slimm609** [comment]
this is a rather interesting one.  When I run it, it produces invalid json but when the tests run it, it produces valid json. 

```
checksec-ubuntu_1  | + /root/checksec --format=json --kernel=kernel.config
checksec-ubuntu_1  | starting custom kernel check for file kernel.config - json
checksec-ubuntu_1  | + /usr/bin/jsonlint-py /root/tests/output.json
checksec-ubuntu_1  | + RET=0
checksec-ubuntu_1  | + cat /root/tests/output.json
checksec-ubuntu_1  | + jq .
checksec-ubuntu_1  | {
checksec-ubuntu_1  |   "kernel": {
checksec-ubuntu_1  |     "KernelConfig": "/proc/config.gz",
checksec-ubuntu_1  |     "randomize_va_space": "full",
checksec-ubuntu_1  |     "nx_protection": "skipped",
checksec-ubuntu_1  |     "protect_symlinks": "yes",
checksec-ubuntu_1  |     "protect_hardlinks": "yes",
checksec-ubuntu_1  |     "protect_fifos": "no",
checksec-ubuntu_1  |     "protect_regular": "no",
checksec-ubuntu_1  |     "ipv4_rpath": "yes",
checksec-ubuntu_1  |     "kernel_heap_randomization": "yes",
checksec-ubuntu_1  |     "gcc_stack_protector": "yes",
checksec-ubuntu_1  |     "gcc_stack_protector_strong": "yes",
checksec-ubuntu_1  |     "gcc_structleak": "no",
checksec-ubuntu_1  |     "slab_freelist_randomization": "yes",
checksec-ubuntu_1  |     "virtually_mapped_stack": "yes",
checksec-ubuntu_1  |     "restrict_dev_mem_access": "yes",
checksec-ubuntu_1  |     "restrict_io_dev_mem_access": "yes",
checksec-ubuntu_1  |     "ro_kernel_data": "yes",
checksec-ubuntu_1  |     "ro_module_data": "yes",
checksec-ubuntu_1  |     "hardened_usercopy": "yes",
checksec-ubuntu_1  |     "fortify_source": "yes",
checksec-ubuntu_1  |     "restrict_dev_kmem_access": "yes",
checksec-ubuntu_1  |     "random_address_space_layout": "yes"
checksec-ubuntu_1  |   },
checksec-ubuntu_1  |   "selinux": {
checksec-ubuntu_1  |     "enabled": "no"
checksec-ubuntu_1  |   },
checksec-ubuntu_1  |   "grsecurity": {
checksec-ubuntu_1  |     "grsecurity_config": "no"
checksec-ubuntu_1  |   }
checksec-ubuntu_1  | }
```

```
root@b32129817b34:~/tests# /root/checksec --format=json --kernel=kernel.config > test.json
root@b32129817b34:~/tests# cat test.json | jq .
parse error: Expected separator between values at line 1, column 374
```

**Comment by jstucke** [comment]
This definitely sounds strange. What could be the difference when running the test? Could there be side effects from other tests? 

Since the problem seems to be a missing comma, could it be that there are no entries before the `grsecurity` entry when running the tests so that it is valid in that case?

**Comment by slimm609** [comment]
I haven't fully narrowed down the issue yet but I am doing some refactoring of checksec to make it easier to manage and also removing grsecurity support entirely since it was moved to private only a few years ago. I think there is a bug in what it is processing as well as the tested kernel.config should have had grsecurity turned on. The refactoring will make it easier to debug this issue for sure.
