### ISSUE TITLE
--kernel could scan kernel config in non-standard path

### ISSUE THREAD

**Issue by asarubbo** [slimm609/checksec.sh#18]
I have one virtual machine where i build some types of kernel.
I'd like to have something like
./checksec --kernel $KERNEL_CONFIG_PATH

If $KERNEL_CONFIG_PATH is empty, then it scan for /usr/src/linux/.config

**Comment by slimm609** [comment]
There are 2 pull requests for these issues and I will be reviewing and
pulling them in the next few days when I am back at my computer.

**Comment by slimm609** [comment]
the command line kernel can be specified now.   It will check multiple places if you don't specify one.
