### ISSUE TITLE
sysctl is at /usr/sbin/sysctl (rather than /sbin/sysctl) in some distros

### ISSUE THREAD

**Issue by hartwork** [slimm609/checksec.sh#20]
Hi!

There are three places where sysctl is called via `/sbin/sysctl` rather than plain `sysctl` in the current code. Would you mind changing those calls to `sysctl`?

Thanks and best, Sebastian

**Comment by slimm609** [comment]
fixed the path for the 3 sysctl calls checking randomize space.

**Comment by hartwork** [comment]
Thank you! My vote for a soon next release :)

**Comment by slimm609** [comment]
it will be.   There is some clean up that I am working on, just need to finish it up then it will be a new release

**Comment by hartwork** [comment]
I'm considering to add a dedicated package to Gentoo. Feel free to drop me a mail on release so I don't miss the update.

**Comment by slimm609** [comment]
what email do you want me to use?

On Tue, Jan 5, 2016 at 10:41 PM, Sebastian Pipping <notifications@github.com

**Comment by slimm609** [comment]
merged in a some stuff.  I pushed off some of the changes til later since they are cosmetic and not functional changes.  release 1.7.2

**Comment by hartwork** [comment]
Excellent, thank you!

It's package `app-admin/checksec` in Gentoo now, see https://github.com/gentoo/gentoo/commit/bc5a59eb44d1bdc7186dfca7a32758c9d50b5caa .
