### ISSUE TITLE
libc.so detection is broken

### ISSUE THREAD

**Issue by Jamie-Landeg-Jones** [slimm609/checksec.sh#204]
# Issue tracker
 If any of these values are not included, the issue will be closed and not worked

## Issue
You can't use "find /" to find the location of libc.so !

Not only does it take forever, it may still not produce the correct result, as it may find a libc that isn't the "live" version

Far more reliable and efficient to parse the output of (e.g.) `ldd /bin/ls`
```
$ ldd /bin/ls
/bin/ls:
        libutil.so.9 => /lib/libutil.so.9 (0x800254000)
        libncursesw.so.8 => /lib/libncursesw.so.8 (0x80026c000)
        libc.so.7 => /lib/libc.so.7 (0x8002cf000)
```
## Debug Report
include the output of `checksec --debug_report`

n/a

## Command run to produce the error

any

## OS version and Kernel version

n/a

## Debug output

Run the same command as above to reproduce the error but include the --debug flag

e.x  `checksec --debug -f /usr/bin/ls`

n/a

**Comment by disconnect3d** [comment]
+1 on this. Running checksec under wsl is terribly broken and slow due to those find calls.

**Comment by sreschke80** [comment]
My approach is an optional parameter to specify the search location of libc as file or path.
https://github.com/slimm609/checksec.sh/pull/206
