### ISSUE TITLE
Resolve use of GNU seq in favor of Bash intrinsics

### ISSUE THREAD

**Issue by hartwork** [slimm609/checksec.sh#21]
When running checksec through strace, I can see 80 forks/calls to GNU seq. These forks could be saved by moving to Bash brace expansion. I could imagine a noticeable speed-up. What do you think?

Best, Sebastian

**Comment by slimm609** [comment]
in order to use expressions in a loop (every instance of seq currently used in a loop) I would have to echo and eval the expression which would require a fork.  So it doesn't actually speed it up any. 

for i in $(eval echo {$a..$b})
instead of 
for i in $(seq $a $b)

**Comment by hartwork** [comment]
Are you sure?

```
# echo $SHELL
/bin/bash

# type eval
eval is a shell builtin
```

**Comment by slimm609** [comment]
its the $() that forks it to a sub process

**Comment by hartwork** [comment]
Are you sure? :)

```
# strace -F -eprocess bash -c "eval 'echo {1..3}'"
execve("/bin/bash", ["bash", "-c", "eval 'echo {1..3}'"], [/* 75 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x7f5b026bb700) = 0
1 2 3
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by hartwork** [comment]
Wait a sec, it doesn't have the braces...

**Comment by slimm609** [comment]
do it in a loop

**Comment by hartwork** [comment]
```
# strace -F -eprocess bash -c 'for i in $(eval "echo {1..3}"); do echo "<$i>"; done'
execve("/bin/bash", ["bash", "-c", "for i in $(eval \"echo {1..3}\"); "...], [/* 75 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x7efc8c44d700) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7efc8c44d9d0) = 25256
strace: Process 25256 attached
[pid 25256] exit_group(0)               = ?
[pid 25256] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=25256, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 25256
wait4(-1, 0x7ffd0d4704d0, WNOHANG, NULL) = -1 ECHILD (No child processes)
<1>
<2>
<3>
exit_group(0)                           = ?
+++ exited with 0 +++
```
I don't see a fork for eval. What am I missing?

**Comment by slimm609** [comment]
#!/bin/bash

for i in $(eval echo {1..3}); do
  echo $i
done

1
2
3

j=3
for i in {1..$j}; do
  echo $i
done

{1..3}

**Comment by hartwork** [comment]
I'm not sure what your last comment is meant to say. Could you spell it out for me? Should I try to make a patch?

**Comment by slimm609** [comment]
#!/bin/bash

j=3
for i in $(eval echo {1..3}); do
  echo $i
done

for i in {1..$j}; do
  echo $i
done

run that in bash

**Comment by hartwork** [comment]
That alone does not work, yes. Quoting `man bash` (version 4.3+), the reason seems to be that braces are expanded before variables are:
> The order of expansions is: brace expansion; tilde expansion, parameter and variable expansion, arithmetic expansion, and command substitution (done in  a  left-to-right  fashion);  word splitting; and pathname expansion.

You can combine the two, though:
```
# bash -c 'j=3; for i in $(eval "echo {1..$j}"); do echo "<$i>"; done'
<1>
<2>
<3>
```

**Comment by hartwork** [comment]
If you would rather avoid `eval`, there should be a flavour of for loop in Bash to make it work without `eval`.

**Comment by slimm609** [comment]
correct, but the subprocess comes from the $() around the eval.   I can move it over to {} with eval, but it will still fork

**Comment by hartwork** [comment]
I guess I mis-read the output in https://github.com/slimm609/checksec.sh/issues/21#issuecomment-169388118 then. I guess you are right.
Alright, let's do it without eval and without $(). Would you rather make a patch yourself or do you want me to give it shot?

**Comment by slimm609** [comment]
if you want to give it a shot please do. Im not sure if we can because of the order of operations.  You need to do variable expansion, then math, then iteration for the loop

**Comment by hartwork** [comment]
Alright, let me have a closer look.

**Comment by hartwork** [comment]
Please feel free to `git am` this patch if you like it:
[0001-Resolve-use-of-GNU-seq-for-loops-issue-21.patch.txt](https://github.com/slimm609/checksec.sh/files/80193/0001-Resolve-use-of-GNU-seq-for-loops-issue-21.patch.txt)

**Comment by slimm609** [comment]
thanks.  checking it now.  here is a quick test of the difference. it did reduce the number of calls and sped it up a bit as well. 

./checksec --proc-all > /dev/null  2.50s user 2.80s system 114% cpu 4.619 total
./checksec.test --proc-all > /dev/null  2.30s user 2.70s system 116% cpu 4.286 total

**Comment by slimm609** [comment]
merged in

**Comment by hartwork** [comment]
Looks like 2ec4bb53e8a9c4ce1ccf386852e57928ef8188b9. Excellent! Closing.
