### ISSUE TITLE
Distinction between fortify source level

### ISSUE THREAD

**Issue by asarubbo** [slimm609/checksec.sh#210]
Hello,

since a while FORTIFY_SOURCE=3 was added:
https://developers.redhat.com/blog/2021/04/16/broadening-compiler-checks-for-buffer-overflows-in-_fortify_source

I didn't dig into it to understand if it is possible to distinguish between 2 and 3 but would be great report which level of fortify has an elf.

Thanks

**Comment by Artoria2e5** [comment]
The extra `__builtin_dynamic_object_size` bit may or may not show up as a symbol. It probably doesn't if we are thinking performance...

**Comment by petervas** [comment]
@slimm609 I think this can be closed. There does not seem to be a stable way to detect the level currently.

**Comment by slimm609** [comment]
Yes, This can be closed.  After a pretty large amount of investigation, a way to detect the level could not be accurately identified
