### ISSUE TITLE
Small text patch for readme

### ISSUE THREAD

**Issue by hartwork** [slimm609/checksec.sh#22]
```
--- to check executable properties like (PIE, RELRO, PaX, Canaries, ASLR, Fortify Source)
+++ to check properties of executables (e.g. ASLR/PIE, RELRO, PaX, Canaries, Fortify Source)
```

**Comment by slimm609** [comment]
fixed it, and another grammatical error.   Thanks!

**Comment by hartwork** [comment]
Maybe still turn "of the executable" to
a) "of a given executable"
b) "of an executable"
c) "of executables"

and group PIE and ASLR together, if the are the same thing. Just my two cents.

**Comment by slimm609** [comment]
im fixing the first part, but ALSR and PIE are 2 different things( though similar).  A kernel can have ASLR but not PIE.

**Comment by hartwork** [comment]
Okay cool.

**Comment by slimm609** [comment]
you should have gotten a tag notification from the release.   Let me know if it worked

**Comment by hartwork** [comment]
It didn't work, it seems.

1.7.3 in Gentoo now: https://github.com/gentoo/gentoo/commit/fff7f104b84e2b49f21cd24ff9c54dfb5e380417

**Comment by slimm609** [comment]
1.7.4 is now released.  Added man page and zsh completion.  along with several other cleanups.   should be the last release for at least a little while 

added a variable for you.

set 
pkg_release=false
to true and it will disable the --update/--upgrade option, so that it can be updated by the package update process rather then with the command line option.

**Comment by vaeth** [comment]
> added a variable for you

Great! I didn't dare to ask about it, because so much work was spent to add the update feature...

> It didn't work, it seems

Being informed about releases never worked for me in github.

BTW, in the mv overlay, I implemented also src_test, but currently both provided test scripts fail, see issue #28

**Comment by hartwork** [comment]
> set `pkg_release=false` to `true` and it will disable the `--update/--upgrade` option, so that it can be updated by the package update process rather then with the command line option. 
Thanks and thanks for the man page too!

Since the test are reported failing I have bumped without tests in Gentoo for now (https://github.com/gentoo/gentoo/commit/bf0d4b1ee9a4f0d04936df63ea44a4fa439ea38d).
