### ISSUE TITLE
 Use sysctl to test the settings of grsecurity

### ISSUE THREAD

**Issue by HacKurx** [slimm609/checksec.sh#24]
Hi,

Actually you use /proc/config.gz for testing grsecurity but the kernel options can be disabled by the user via a sysctl file in "/etc/sysctl.d/".

It would be best to test what is really active on the system.

Thanks, best regards

Here is the list of variables.
[sysctl_options_for_grsecurity.txt](https://github.com/slimm609/checksec.sh/files/82783/sysctl_options_for_grsecurity.txt)

**Comment by slimm609** [comment]
this is a long addition and not a quick change that will take some time to add.   this adds a different conditional check, but I will look into implementing it.

**Comment by HacKurx** [comment]
Perfect. Yes, I give the work ^^
If you want my help no problem ;)

**Comment by HacKurx** [comment]
Very quickly here the values to be tested:
[test001-sysctl-grsec.txt](https://github.com/slimm609/checksec.sh/files/82821/test001-sysctl-grsec.txt)

**Comment by HacKurx** [comment]
The simplest might be something like:
[No tested.txt](https://github.com/slimm609/checksec.sh/files/83289/No.tested.txt)

**Comment by slimm609** [comment]
not complete yet, but working.  Still need to finish fixing json and xml formats

**Comment by HacKurx** [comment]
Thanks but that did not work, Here errors:
    grsecurity.audit_chdir:		 0Disabled
    grsecurity.audit_group:		 Disabled
    grsecurity.audit_mount:		 0Disabled
    grsecurity.audit_ptrace:		 1Disabled

I have made some changes:
[checksec.patch.txt](https://github.com/slimm609/checksec.sh/files/104666/checksec.patch.txt)

**Comment by HacKurx** [comment]
It works well but it's not a good visibility. In the future it might be seen to create two separate options:
--kernel-kconfig
--kernel-sysctl

**Comment by slimm609** [comment]
Grsec is the only part with lots of Sysctl options so there is no reason to
create a entire new function for just part of grsec

**Comment by HacKurx** [comment]
Good, it remains just a few minor errors :)
![error](https://cloud.githubusercontent.com/assets/4661917/12641394/9ab40f22-c5af-11e5-98a7-711e0ab6debc.png)

Must be replaced by:
if [ "$grcheck" -ne 0 2> /dev/null ]; then

Finally, it lacks some variables, thank you to use this list:
[complet_list.txt](https://github.com/slimm609/checksec.sh/files/108010/complet_list.txt)

Thank you very much

**Comment by slimm609** [comment]
give it a try now.    

if [ "$grcheck" -ne 0 2> /dev/null ]; then  will not work.  If grcheck is null then you get an bash error for a if statement being [ "" -ne 0 ]   but it should work now.

**Comment by HacKurx** [comment]
Perfect.
