### ISSUE TITLE
both test scripts fail in 1.7.4

### ISSUE THREAD

**Issue by vaeth** [slimm609/checksec.sh#28]
json-checks.sh has a trivial typo (/dev/bull instead of /dev/null).
xml-checks.sh fails for a more serious reason: It seems that a spurious ":" is output near the beginning:

output.xml:2: parser error : Start tag expected, '<' not found
: <procs><proc name='init' pid='1' relro="full" canary="yes" seccomp="no" pax="y
^

**Comment by slimm609** [comment]
can you see which check it is.   I am not getting that check failure on my debian box.  I tried to hand check proc (since that what it seems to be coming from) but couldn't find it. 

starting proc-all check - xml
starting kernel check - xml
starting custom kernel check - xml
starting file check - xml
starting fortify-file check - xml
starting dir check - xml
All XML validation tests passed xmllint

**Comment by slimm609** [comment]
fixed the /dev/bull error though,   thanks

**Comment by slimm609** [comment]
give that a try.   I think i found it, there was a random printf ": " in there, that I couldn't trace back to having any reason of being there.

**Comment by vaeth** [comment]
> the exit status is checking the exit of the xmllint or jsonlint

Yes, the xml-checks.sh script prints an error (due to xmllin error), and it exits. But its exit status is 0 (and thus one must look at the output to understand whether the tests succeeded. In particular, the exit status cannot be used by the package manager to check whether the tests succeeded).
An analogous assertion holds for the json-checks.sh script: Every "exit" returns status 0, even those which occur in an error situation.

I am running gentoo.

**Comment by slimm609** [comment]
The exit is exiting the check script if the exit status ($?) of the
previous command is anything other than 0. That exit is exiting only after
a previous failure. But it should be changed to somethings other than 0

**Comment by vaeth** [comment]
Not sure whether we understand each other correctly. I mean that there should be always something like
`if [ $? != 0 ]; then`
` echo "fortify-file xml validation failed"`
` exit `**1**
`fi`
(currently the `exit` is without **1**)

**Comment by slimm609** [comment]
are these still failing for you?

**Comment by vaeth** [comment]
The fact that /bin/ls is still used causes an error here. (As mentioned above, /bin/ls has become a shell wrapper in current coreutils.)
```
proc-all check - xml
starting kernel check - xml
sysctl: permission denied on key 'fs.protected_symlinks'
sysctl: permission denied on key 'fs.protected_hardlinks'
sysctl: permission denied on key 'kernel.pax.softmode'
starting custom kernel check - xml
sysctl: permission denied on key 'fs.protected_symlinks'
sysctl: permission denied on key 'fs.protected_hardlinks'
sysctl: permission denied on key 'kernel.pax.softmode'
starting file check - xml
output.xml:2: parser error : Start tag expected, '<' not found
Error: Not an ELF file: /bin/ls: a /usr/bin/coreutils --coreutils-prog-sheb
^
file xml validation failed
```
Appart from this, all tests (including exit status) appear to work correctly now

**Comment by slimm609** [comment]
i changed the order.   damn shell wrappers. lol

**Comment by vaeth** [comment]
In the first test in xml-checks.sh (#check xml for file) /bin/ls is used unconditionally.

**Comment by slimm609** [comment]
should be good now.

**Comment by vaeth** [comment]
Yep, works now (with demjson-2.2.2).

However, I had just upgraded to demjson-2.2.4, and with this the following 3 checks fail:
proc-all, fortify-file, dir

The reason is that jsonlint of demjson-2.2.4 returns a nonzero exit status already for warnings.

A workaround (which works with both versions of demjson) is to pass the option
 --allow duplicate-keys
for these 3 tests to jsonlint, 'though perhaps the warning should be taken more seriously.
