### ISSUE TITLE
Please uncompress man page "checksec.7" in Git

### ISSUE THREAD

**Issue by hartwork** [slimm609/checksec.sh#29]
Hi! I noticed that the man page at
https://github.com/slimm609/checksec.sh/blob/master/extras/man/checksec.7.gz
is compressed in Git. I can think of quite a few downsides of that (..) but only a single upside with size of a direct download. On a side note, Linux distros like and do take care of man page compression themselves. Unless I am missing something, I would ask to store the man page uncompressed (and ideally even to have it be generated from AsciiDoc or something).

Thanks and best, S

**Comment by slimm609** [comment]
i uncompressed it for the source.   I haven't messed with asciidoc before.

**Comment by hartwork** [comment]
Thanks!

Looks fixed to me, closing.
For the record, commit is a4cce2901b87cd94ce41e9e7852d057ab8df15e2.
