### ISSUE TITLE
DEBUG_RODATA and DEBUG_STRICT_USER_COPY_CHECKS no longer exist in newer kernels

### ISSUE THREAD

**Issue by tpruzina** [slimm609/checksec.sh#39]
Title says it all, `DEBUG_RODATA` was renamed/split to `STRICT_KERNEL_RWX` and `STRICT_MODULE_RWX`.
https://github.com/torvalds/linux/commit/7bb033829ef3ecfc491c0ed0197966e8f197fbdc

`CONFIG_DEBUG_STRICT_USER_COPY_CHECKS` got removed as it's not needed.
https://github.com/torvalds/linux/commit/0d025d271e55f3de21f0aaaf54b42d20404d2b23

In other news, `HARDENED_USERCOPY` and `HARDENED_USERCOPY_PAGESPAN` were added and I do believe they are roughly equivalent to PAXes `PAX_USERCOPY`. 
https://github.com/torvalds/linux/commit/f5509cc18daa7f82bcc553be70df2117c8eedc16

Do you mind updating your shellscript to reflect these?

**Comment by slimm609** [comment]
DEBUG_RODATA should would on older kernels and STRICT_[KERNEL,MODULE]_RWX should be supported on newer kernels

CONFIG_DEBUG_STRICT_USER_COPY_CHECKS is still supported for older kernels but shouldn't show as an issue on newer kernels.    

Will work on USERCOPY.

**Comment by slimm609** [comment]
added usercopy
