### ISSUE TITLE
eu-readelf support seems a bit off

### ISSUE THREAD

**Issue by JoshLitt** [slimm609/checksec.sh#45]
I run `checksec -f` on the exact same binary on two different systems. One has readelf, the other has eu-readelf. The one with readelf says PIE enabled, and the one with eu-readelf says DSO.  This seems to be because it's running `$readelf -d` and looking for '(DEBUG)', but eu-readelf doesn't use parentheses, so it would need to look for 'DEBUG' instead.

I also see the function counts from the fortify check (-ff) are doubled for unstripped executables, but that's probably unrelated to eu-readelf.

**Comment by slimm609** [comment]
I just added a fix for this.    I just updated for to use 'DEBUG' instead of '(DEBUG)'  and it looks to be working locally.   Please test and let me know.   Sorry for the late response.
