### ISSUE TITLE
debug_report lack of meaningful exit code

### ISSUE THREAD

**Issue by pantocrator27** [slimm609/checksec.sh#46]
I am running checksec with debug_report in a minimal linux environment to test dependencies installed in my environment and noticed that if a required binary is not present, debug_report exists with a normal exit code.  I am thinking this should exit with a non-zero exist code.

**Comment by slimm609** [comment]
this is fixed.   if any files fail during the check it sets a non-zero exit code

**Comment by pantocrator27** [comment]
thanks!
