### ISSUE TITLE
[QUESTION] read -r -d '' PUBKEY appears to result in non-zero exit code.  

### ISSUE THREAD

**Issue by pantocrator27** [slimm609/checksec.sh#47]
https://github.com/slimm609/checksec.sh/blob/master/checksec#L91 seems to error out when calling checksec using `/bin/bash -xe checksec`.  Using the `-e` flag, this is most likely due to a non-zero exit code being returned from this line.  If I have time, I will investigate further.

**Comment by pantocrator27** [comment]
I was attempting to pass the `-xe` flags to `/bin/bash` as a response to https://github.com/slimm609/checksec.sh/issues/46

**Comment by slimm609** [comment]
this should be fixed.    the pubkey should return 0 now

**Comment by pantocrator27** [comment]
thanks!
