### ISSUE TITLE
fetch bash function security

### ISSUE THREAD

**Issue by pantocrator27** [slimm609/checksec.sh#48]
If security is of the essence here and you are attempting to check the script against a signed signature, should we also not be disabling TLS verification here: https://github.com/slimm609/checksec.sh/blob/master/checksec#L110-L122

**Comment by slimm609** [comment]
what security do you gain by using TLS verification?       

if you download via https w/ tls verification and the signature fails, its been tampered

if you download via https w/o tls verification and the signature fails, its been tampered

if you download via https w/ tls verification and the signature passes, its good.

if you download via https w/o tls verification and the signature passes, its good. 

the update function uses the public cert to validation the file.   The cert is included in the script so it doesn't care where or how the update is download, just that it passes the signature verification 

https://github.com/slimm609/checksec.sh/blob/master/checksec#L1103-L1120

**Comment by pantocrator27** [comment]
Actually I agree with your assessment.  I just get nervous whenever anything disables TLS :)
