### ISSUE TITLE
Add completion to checksec

### ISSUE THREAD

**Issue by lzutao** [slimm609/checksec.sh#52]
I cannot use completion to complete statements when using `checksec`, could you fix it?

**Comment by slimm609** [comment]
You are welcome to add it and I will merge a PR but I won't have time to add it anytime soon

**Comment by lzutao** [comment]
I was wondering why the complete function not working in checksec packages on Arch Linux, but on Ubuntu when I cloning it from Github and installing it, it just worked.

**Comment by slimm609** [comment]
the _checksec file for zsh has all the autocomplete stuff.    I am guessing it has something to do with that.   I am not the one maintaining the arch package so I am not sure on that specific issue.
