### ISSUE TITLE
Man page implies '--dir' option is recursive

### ISSUE THREAD

**Issue by CalumMcCall** [slimm609/checksec.sh#54]
The man page states:

> -d or --dir
                  Recursively  checks  all executable files in the directory for security features compiled
                  into the executables

I'm not sure what's meant exactly by this statement, as in my tests, checksec does not check subdirectories recursively. It only checks executables in the directory given. Is this intended behaviour? My expectation was that it would recursively check subdirectories.

**Comment by slimm609** [comment]
give it a try now.     should be fixed

**Comment by rc-matthew-l-weber** [comment]
One other bug with this.  Please use . instead of $(tempdir) in the find () used to locate all the files.  Then you can use relative paths

**Comment by slimm609** [comment]
Tested and can not reproduce this issue.  closing
