### ISSUE TITLE
Rev-2017080801 released without a new version tag

### ISSUE THREAD

**Issue by saildata** [slimm609/checksec.sh#56]
Package maintainers rely on the git tag for recognizing release points. The Arch version is now out of date because this update wasn't tagged.

Thanks for the continued hard work and great project. --Cheers

**Comment by saildata** [comment]
What is the status of this ticket? We need to use version tags for this to be properly included in downstream repos. Thanks

**Comment by slimm609** [comment]
I can create a new release for this one.   I was still testing a few things so it wasn't a "final" version release but I will complete some additional testing and try to get a new release up within 24 hours.

Thanks!

**Comment by slimm609** [comment]
updated to 1.8.0
