### ISSUE TITLE
Requesting releases and drop of ".sh" extension

### ISSUE THREAD

**Issue by hartwork** [slimm609/checksec.sh#6]
Hi!
My understanding is that yours is the most active successor to the original checksec.sh 1.5.
I believe checksec.sh should go into Linux distributions at some point as a proper package.
To make that smoother I would ask to
* get rid of the `.sh` extension, since that looks wierd in a ``$PATH` folder
* start making release tags

Then updating process may need changes then, which you know best.
If `.sh` needs to stay alive to not break updates of existing installations, maybe a simple Automake-based build system installing `checksec.sh` as `checksec` would be cool.

What do you think?

**Comment by slimm609** [comment]
.sh dropped and will start tagging releases

**Comment by hartwork** [comment]
Cool!

Related commits:
* fb365cf57fcdbc1a985d0d78ef8779b91b20fd35
* b352ad54a85f83fc842f51668b515824460fa2ef
* 3665d4a23cb8d33a0db6937c98a2f3967a772f00
