### ISSUE TITLE
checksec support for go-lang compiler

### ISSUE THREAD

**Issue by srikanth007m** [slimm609/checksec.sh#60]
Hi,
Is there any support of existing checksec to bins/procs compiled using go-lang. So the flags may not be reflecting in Makefile similar to what gcc uses. 

Any suggestions?

**Comment by slimm609** [comment]
checksec can scan go-lang binaries fine.    There is a flag in go build for -buildmode=PIE.   That will use enable some of the features that gcc uses for protection
