### ISSUE TITLE
need a option for prefix when testing offline filesystems?

### ISSUE THREAD

**Issue by rc-matthew-l-weber** [slimm609/checksec.sh#62]
When building and testing a filesystem of a embedded system offline, it would be nice to provide a prefix so the script understands to look in a specific folder at a specific libc, etc.  I'm not sure of the full impact of adding this option and which checksec options can't be assumed to work offline.  Maybe a offline mode with prefix option ?  Thoughts?  I can definitely create a pull request to support adding the prefix but thought a offline filesystem option might be something else to debate as some features assume you're running this on the executing system.

**Comment by rc-matthew-l-weber** [comment]
Oh interesting, didn't think about it that way.  We'll do some testing.

**Comment by rc-matthew-l-weber** [comment]
Noted, we'll look at doing that.  The only challenge there is dealing with a cross arch build of a filesystem and not having the right readelf/elfdump tools built native for that env.

As part of testing, I noticed a relative path issue with -d option.  Noted here: https://github.com/slimm609/checksec.sh/issues/54

**Comment by xiaomiguo** [comment]
Hello, we use checksec.sh to check stack canary, process check considers the symbol table, but the file check consider not only symbol table but also dynamic symbol table.  This is confusing me.

**Comment by slimm609** [comment]
merged in #54
