### ISSUE TITLE
feature request: add fortified / fortify-able function to --file output 

### ISSUE THREAD

**Issue by boos** [slimm609/checksec.sh#7]
It would be nice to add 
* Number of fortified functions in the executable
* Number of FORTIFY-able functions in the executable

in the output of checksec.sh --file , in that way when we will use checksec.sh --file we will have full control of current security measures applied to the binary.

**Comment by slimm609** [comment]
merged and signed --  checksec --update will pull the latest revision.   The only error was a comma on the runpath part.   Thanks for the contribution!

**Comment by boos** [comment]
Cool, I saw in the changelog you mentioned me, could you use my real name/surname please ?

**Comment by slimm609** [comment]
done
