### ISSUE TITLE
'checksec -d' creates empty file named '755' in  chosen dir

### ISSUE THREAD

**Issue by Maryse47** [slimm609/checksec.sh#72]
```
$ ls /usr/bin/755
"/usr/bin/755": No such file or directory (os error 2)
$ checksec -d /usr/bin/
...
/usr/local/sbin/checksec: line 291: 755: Permission denied
...
$ sudo checksec -d /usr/bin/
...
$ ls /usr/bin/755
755
```

**Comment by slimm609** [comment]
What version of Linux are you running it on?

**Comment by Maryse47** [comment]
Arch Linux + latest checksec git snapshot

**Comment by Maryse47** [comment]
It doesn't happen with 1.8 release.

**Comment by Maryse47** [comment]
This commit causes this issue: https://github.com/slimm609/checksec.sh/commit/f3d9f06ca0b1d2149451ab0d55f8c3d31e16f493

**Comment by slimm609** [comment]
give that a try and see if that fixes the issue.    I couldn't get it to create the 755 file but it did error with some other errors which i resolved.

**Comment by Maryse47** [comment]
That fixes it, thanks!
