### ISSUE TITLE
use official arch docker image

### ISSUE THREAD

**Issue by anthraxx** [slimm609/checksec.sh#74]
Hi,

I have noticed you are using `base/archlinux` which is an unofficial user built image. Could you consider using the officially maintained and published variant `archlinux/base` instead? Yeah the clash of those two names sucks :smirk_cat: 

PS: Please also use `pacman -Syu --noconfirm` instead of just `-Sy` as that only updates the  database. If you then just install packages with `-S` without upgrading you technically do a partial upgrade which is not supported by Arch Linux and may result in incompatibilities and failed soname linkage and therefor major breakage.

**Comment by Maryse47** [comment]
I created PR for this

**Comment by slimm609** [comment]
awesome.  Thanks.   

The docker images are only used to be able to test to ensure that stuff is working properly and not throwing errors.

**Comment by anthraxx** [comment]
nice, thanks :)
