### ISSUE TITLE
spelling "checksec.sh" versus "checksec" in the README.md

### ISSUE THREAD

**Issue by toralf** [slimm609/checksec.sh#76]
when did the suffix vanished?

**Comment by slimm609** [comment]
Jan 2015.  Almost 4 years ago

**Comment by toralf** [comment]
Hhmn, the README.md still spells "checksec.sh " instead of "checksec"

**Comment by slimm609** [comment]
That’s an easy fix

**Comment by slimm609** [comment]
I will fix soon

**Comment by slimm609** [comment]
resolved in latest release
