### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by tawmoto** [slimm609/checksec.sh#92]
Hello, 

In README it says that it should work on macOS by installing "binutils", but binutils does not install readelf, which is required by checksec, therefore I get the error "readelf not found! It's required for most checks".

Should it work on macOS?
Thanks

**Comment by disconnect3d** [comment]
You might try:
```
brew install binutils
sudo ln -s /usr/local/bin/greadelf /usr/local/bin/readelf
```
(via https://github.com/lovell/sharp/issues/602#issuecomment-253767332)

**Comment by Prasildas-AHM** [comment]
I am still getting the issue on the same.  even after trying the above

Error:
readelf is a required tool for almost all tests. Aborting...

**Comment by slimm609** [comment]
did you do the part to add it to your path like it says?

```bash
echo 'export PATH="/usr/local/opt/binutils/bin:$PATH"' >> ~/.bash_profile
```

just tested and it works fine once you do that

**Comment by tawmoto** [comment]
TBH, I thought it works macOS Mach-O binaries, but it does not.

**Comment by slimm609** [comment]
I just updated the readme to remove osx support  

The tools run when you install the GNU versions but they don't actually check anything because Mach-O binaries are completely different as well as the kernel
