### ISSUE TITLE
false positives about the canary detection

### ISSUE THREAD

**Issue by asarubbo** [slimm609/checksec.sh#93]
## Issue
While glibc is compiled with SSP, I got some false positives because of /usr/lib/libc_nonshared.a.
There is a downstream bug (not about checksec itself) that talks about: https://bugs.gentoo.org/679788

## Command run to produce the error
To reproduce the error you need to have glibc compiled with SSP and then compile something like man-db http://www.nongnu.org/man-db/
You will have the canary detected on /usr/bin/man, while man itself was not compiled with -fstack*

## OS version and Kernel version
Gentoo, kernel 4.19.27

## Debug output
So while running "readelf -sW /usr/bin/man | grep "__stack_chk_fail" I got:
~~~
~ # readelf -sW /usr/bin/man | grep "__stack_chk_fail"
    45: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __stack_chk_fail@GLIBC_2.4 (4)
~~~

The fact is, for what I understood, that __stack_chk_fail does not come from a function in the man binary, but from something in the libc itself that is used into man.

**Comment by slimm609** [comment]
Can you please validate this is still an issue with the latest version.    There were some updates around that code

**Comment by slimm609** [comment]
closing issue.  reopen if still an issue
