### ISSUE TITLE
New release needed from current master branch.

### ISSUE THREAD

**Issue by codytubbs** [slimm609/checksec.sh#96]
# Issue tracker
 If any of these values are not included, the issue will be closed and not worked

## Issue
New release needed from current master branch.
Runtime using current branch (1.11.*) is several hours faster than 1.9.0. (e.g. ~30 minutes vs ~5 hours).
The optimizations merged since 1.9.0 have made this tool dramatically faster across the board.

## Debug Report
n/a

## Command run to produce the error
n/a

## OS version and Kernel version
n/a

## Debug output
n/a

**Comment by slimm609** [comment]
https://github.com/slimm609/checksec.sh/releases/tag/1.11.1
